slug: nchsdb
visit: encounter
charts:
- chart: nsrr_sex
  title: Sex
- chart: nsrr_race
  title: Race
- chart: nsrr_ethnicity
  title: Ethnicity
webservers:
  - name: production
    url: https://sleepdata.org
  - name: staging
    url: https://staging.partners.org/sleepdata.org
